payloadcms/website

src/components/Announcements/index.module.scss
src/components/Announcements/index.tsx

New announcement banner was covered by docs menu on mobile.
Before:
After:

fix: announcement hidden by docs nav on mobile

---

src/app/new/(checkout)/useDeploy.tsx
src/components/CreditCardSelector/index.tsx

The `new-card` id was preventing the new payment intents from being made when switching between two teams without existing payment methods. This is because the value `new-card` as useEffect dependency was never new. The fix is to generate uuids for new cards, specifically when changing teams. This will force the effect to run and a new payement intent to be made.

fix: refreshes payment intent when switching teams without existing payment methods

---

src/app/new/(checkout)/Checkout.tsx
src/app/new/(checkout)/useCreateSubscription.ts
src/app/new/(checkout)/useDeploy.tsx

Creates subscriptions only on deploy. Previously we were using a hook to make the payment intent, but this was creating a new subscription each time the checkout page was loaded or the payment methods were changed. This was not a problem pre-trials because the subscriptions were left "incomplete" until a successful payment.

fix: subscription creation

---

src/app/cloud/[team-slug]/[project-slug]/(tabs)/(overview)/DeploymentLogs/index.tsx
src/payload-cloud-types.ts

There were scenarios where a build could fail, but the build logs indicator would still show green.
- Build logs now show red on deploymentStatus of `ERROR`
- Hide deploy logs tab in when deploymentStatus `ERROR`. This was showing with the default log message in build failure states.
Uses new fields introduced in payloadcms/cloud-cms@845f179c1ca0071af13e4be3dcbbf314adadb9b2

fix: indicator color properly show red on build failure

---

src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/(build-settings)/client_page.tsx
src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/plan/client_page.tsx
src/app/cloud/[team-slug]/settings/client_page.tsx
src/app/new/(checkout)/Checkout.tsx
src/components/BranchSelector/index.tsx
src/components/TeamSelector/index.tsx
src/forms/Label/index.tsx
src/forms/fields/Checkbox/index.module.scss
src/forms/fields/Checkbox/index.tsx
src/forms/fields/Number/index.tsx
src/forms/fields/Phone/Input.tsx
src/forms/fields/RadioGroup/index.tsx
src/forms/fields/Secret/index.tsx
src/forms/fields/Select/index.tsx
src/forms/fields/Text/index.tsx
src/forms/fields/Textarea/index.tsx
src/forms/types.ts
src/forms/useFormField/index.tsx
src/utilities/isNumber.ts

Reduces the amount of overhead the useFormField hook needs to know about. Opts for a different approach allowing the value to be used and passed into the callback. The callbacks can then determine what kind of validation they need to perform.

chore: simplifies input validation functions

---

src/components/BranchSelector/index.tsx
src/components/BranchSelector/reducer.ts
src/forms/fields/Select/index.tsx

Fixes a bug in Cloud where repos with more than 30 branches were unable to paginate through to select deeply listed branches.

feat: paginates github branch selector

---

src/app/new/(checkout)/useCreateSubscription.ts
src/app/new/(checkout)/useDeploy.tsx

Newly imported projects using custom deployment branches were falling back to `main` and crashing the initial deployment. This fixes that.

fix: stale project in useCreateSubscription hook

---

src/components/RichText/Serialize/index.tsx

May be missing something, but pretty sure the prop for `newTab` is missing from the serializer for CMSLink.
Hope this helps ;-)

fix: add prop for newTab to serialize CMSLink

---

src/components/CreditCardList/index.tsx

Hides the menu controls for the default payment method so the user cannot delete the default before reassigning another card.
Note: I removed the logic around the buttons within the dropdown menu because we are now checking for default at the level above.

chore: hides menu for default payment method

---

src/app/(pages)/docs/[topic]/[doc]/page.tsx
src/app/(pages)/docs/[topic]/page.tsx

`/docs/fields` will now redirect to `/docs/fields/overview` for example, instead of 404 like it currently does.

chore: redirects doc topics to first doc of topic instead of 404

---

src/app/(pages)/blog/[slug]/AuthorsList/index.module.scss
src/app/(pages)/blog/[slug]/BlogPost/index.module.scss
src/app/(pages)/blog/[slug]/BlogPost/index.tsx
src/app/(pages)/blog/[slug]/page.tsx
src/blocks/RelatedPosts/index.module.scss
src/blocks/RelatedPosts/index.tsx
src/components/RenderBlocks/index.tsx
src/components/cards/ContentMediaCard/index.module.scss
src/components/cards/ContentMediaCard/index.tsx
src/components/cards/types.ts
src/graphql/posts.ts

Builds a related posts block which renders at the bottom of each blog post. These are hand selected in the post itself. In the future, we can build out some sort of auto population based on taxonomy, or most recent, etc. Here is what this component looks like:
When only 1:
When 3 or more:

feat: builds RelatedPosts block

---

src/app/cloud/[team-slug]/settings/(tabs)/invoices/client_page.tsx
src/app/cloud/[team-slug]/settings/(tabs)/subscriptions/client_page.tsx
src/utilities/price-from-json.ts

Closes #209 
Updates the `price-from-json` function to use the `data[0]` object from the parsed `priceJSON`.
Note:
I wasn't able to see the changes on the invoice route, because there wasn't an actual Stripe price for the projects in my dev environment. I was able to see them in the Configure page:
Before:
After:
The Invoices page uses a similar object structure:
https://github.com/payloadcms/website/blob/ee1d13612f55e3b03f32c40348cac9da4133010d/src/app/cloud/%5Bteam-slug%5D/settings/(tabs)/invoices/client_page.tsx#L86

uses values from data array instead of priceJSON object

---

src/app/(pages)/blog/[slug]/BlogPost/index.tsx
src/app/(pages)/case-studies/[slug]/client_page.tsx
src/components/Breadcrumbs/index.tsx
src/components/Hero/Default/index.tsx
src/components/Hero/Livestream/index.tsx

fix: disabled breadcrumb ellipsis on blog, case studies, default hero

---

src/css/app.scss

Adds `-webkit-text-size-adjust: 100%;` to prevent browsers from scaling font-sizes by default.
| Before | After |
| --- | --- |
| ![IMG_2419](https://github.com/payloadcms/website/assets/89618855/62d3d371-c68b-4515-85bc-3123a447bbc3) | ![IMG_2420](https://github.com/payloadcms/website/assets/89618855/d62f4f82-d29b-4ea0-acb1-0d57f47ae6c1) |

Fix: disables browser font-size adjustments

---

src/app/cloud/[team-slug]/[project-slug]/(tabs)/logs/page_client.tsx

Informs the user when runtime logs are not available.

fix: stop fetching runtime logs before they exist

---

src/app/cloud/_api/fetchInstalls.ts
src/app/cloud/_api/fetchRepos.ts
src/app/cloud/_components/InstallationButton/index.tsx
src/app/cloud/_components/InstallationSelector/components/MenuList/index.module.scss
src/app/cloud/_components/InstallationSelector/components/MenuList/index.tsx
src/app/cloud/_components/InstallationSelector/components/Option/index.module.scss
src/app/cloud/_components/InstallationSelector/components/Option/index.tsx
src/app/cloud/_components/InstallationSelector/components/SingleValue/index.module.scss
src/app/cloud/_components/InstallationSelector/components/SingleValue/index.tsx
src/app/cloud/_components/InstallationSelector/index.module.scss
src/app/cloud/_components/InstallationSelector/index.tsx
src/app/cloud/_components/InstallationSelector/types.ts
src/app/new/clone/[template-slug]/page.tsx
src/app/new/clone/[template-slug]/page_client.tsx
src/app/new/import/page.tsx
src/app/new/import/page_client.tsx
src/utilities/use-popup-window.ts

Fixes the GitHub app installation flow. Previously, when the user had no repos, this was throwing an error on the server and rendering an error page on the client. Now, we safely handle these cases. The following page also needed some updates, it was rendering irrelevant content on the screen, etc. But more importantly, the `InstallationSelector` was far too complex to the point of it being unmanageable. This PR completely removes the `useInstallationSelector` in favor of a more straightforward approach.

fix: github app installation flow

---

src/components/Header/Docsearch/Component.tsx
src/components/Header/Docsearch/index.module.scss
src/components/RelatedHelpList/index.module.scss

Updates icon and prefixes path for blog results in the doc search.
Before
After
Centers related help icon and text
Before
After

chore: updates blog results css in doc search + centers related help list

---

src/components/CMSLink/index.tsx

Fixes an issue where internal links were looking for `reference.value.slug`, causing them to be break.

fix: broken internal links

---

src/components/Breadcrumbs/index.module.scss

fix: updates ellipsis max-width for breadcrumbs

---

src/components/Hero/ContentMedia/index.tsx

Large images were rendering blurry on screens larger than 1920px. This PR fixes that to accommodate for ContentMedia hero's with wide media.

Fix: corrects sizes attribute on hero images

---

src/blocks/CardGrid/index.tsx

Changes the Square Cards block to use 3 columns at all breakpoints, which makes for better responsive sizing for cards with lots of content.
**Before:**
**After:**

fix: better responsiveness for square cards

---

.vscode/settings.json

```
Controls whether auto fix action should be run on file save.
true: Triggers Code Actions only when explicitly saved. This value will be deprecated in favor of "explicit".
```

chore:update vscode settings for deprecated

---

src/components/Code/index.tsx

Fixes the pesky warning about unique keys when using code blocks

chore: Fix prism renderer key warning

---

vercel.json

Because we are now using the Payload Local API for data fetching, rather than `fetch()`, our caching relies on the Vercel Edge Network to cache responses and. This PR updates the cache strategy in our Vercel Edge Network configuration to cache functions for much longer to prevent cache writes for every page visit.

fix: update cache headers for Vercel Edge network

---

src/app/(frontend)/(pages)/[...slug]/page.tsx
src/collections/Pages.ts
src/payload-types.ts

This will allow us to hide specific pages from Google, other crawlers, etc. 
- Added a `noindex` checkbox to Pages collection
- If checked, the meta property will get added to the `<head>` element accordingly

adds noindex checkbox to pages

---

src/components/Header/Docsearch/Component.tsx

If searching for docs, the search hits link to latest documentation regardless of which version of the docs you are currently viewing. This PR modifies the search component to check if the user is currently viewing V2 docs, and modify the hit url to point to the respective V2 docs.
This is a quick solution to let users maintain versions while utilizing search. In the future, we should consider a crawling strategy for versioned docs with the ability to select specific versions, as well as maintaining a user's version preference.

feat: match search hit urls to docs version

---

src/collections/Docs/index.ts
src/payload-types.ts
src/scripts/syncDocs.ts

The mdx <-> Lexical conversion is a somewhat immature feature that still needs to be tested and polished.
At least for now, we are adding a column containing the mdx to the docs collection.
This will help with debugging and testing the conversion. Also, we can refresh the conversion to editorState without fetching every time.  That is what we are doing now, causing the Github API rate limit to be exceeded easily and frequently.

add mdx field to docs

---

src/components/AfterNavActions/index.tsx
src/components/RefreshMdxToLexicalButton/index.scss
src/components/RefreshMdxToLexicalButton/index.tsx
src/payload.config.ts
src/scripts/syncDocs.ts

This is a continuation of https://github.com/payloadcms/website/pull/419
Add ability to refresh mdx to lexical conversion without the need to fetch again from Github.
Useful for debugging and polishing our converters.

Add ability to refresh mdx to lexical conversion.

---

.gitignore
scripts/fetch-docs.mjs

When writing docs, if you do not already have a `/src/docs` directory, the script would fail while attempting to write to it. Now it checks for that directory and creates one if needed. The reason this could happen is because that directory is ignored from git, and so unless you've previously written to it, you will not have this directory on your machine.

fix: makes doc dir before writing to it and adds to .gitignore

---

scripts/fetch-docs.mjs
scripts/shared.mjs
src/app/(frontend)/(pages)/docs/dynamic/[topic]/[doc]/page.tsx
src/app/(frontend)/(pages)/docs/local/[topic]/[doc]/api.ts
src/app/(frontend)/(pages)/docs/local/[topic]/[doc]/layout.tsx
src/app/(frontend)/(pages)/docs/local/[topic]/[doc]/page.tsx
src/components/DocsNavigation/index.tsx
src/components/RenderDocs/index.tsx
src/components/VersionSelector/index.tsx

Brings back the ability to preview docs from a local repository, bypassing the need to save docs as records in the database. Does by so querying the `payload` repository from your local file system and traversing the `docs` directory. This will output a json file containing all mdx markup which is converted to Lexical before rendering.

feat: local docs

---

scripts/shared.mjs

Adds a new "Custom Components" topic to the docs nav to facilitate the changes made here: https://github.com/payloadcms/payload/pull/10987

feat: adds custom components docs topic

---

src/components/Code/index.tsx

fix: use tsx instead of jsx for code block rendering

---

src/app/(payload)/admin/importMap.js
src/collections/Docs/blocks/resource/index.ts
src/collections/Docs/index.ts
src/collections/Posts.ts
src/components/Drawer/types.ts
src/components/RichText/ResourceBlock/index.module.scss
src/components/RichText/ResourceBlock/index.tsx
src/components/RichText/index.tsx
src/components/blocks/RelatedPosts/index.module.scss
src/components/blocks/RelatedPosts/index.tsx
src/components/cards/ContentMediaCard/index.module.scss
src/components/cards/ContentMediaCard/index.tsx
src/components/cards/types.ts
src/fields/addToDocs/Label.tsx
src/fields/addToDocs/index.module.scss
src/fields/addToDocs/index.ts
src/icons/PlayIcon/index.tsx
src/payload-types.ts
src/payload.config.ts
src/utilities/oxford-comma.ts

Adds a new `Resource` block for linking useful posts and guides in the documentation.
**Example:**
```
<Resource id=" post id goes here " />
```
---

Feat: add Resources block to docs

---

package.json
pnpm-lock.yaml
src/payload-types.ts
src/scripts/generateLLMs.ts

Adds a build script to generate `llms.txt` + `llms-full.txt` files from the [Payload documentation source code](https://github.com/payloadcms/payload/tree/main/docs).
Based on the proposal for "adding a `/llms.txt` markdown file to websites to provide LLM-friendly content."
Full proposal: https://llmstxt.org/
Examples:
https://payload-website-git-feat-llms-txt-payloadcms.vercel.app/llms.txt
https://payload-website-git-feat-llms-txt-payloadcms.vercel.app/llms-full.txt

feat: generate llms.txt/llms-full.txt for Payload documentation

---

src/app/(frontend)/(pages)/docs/fetchTopicsForSidebar.ts

Corrects an issue where Topics without any docs were still showing up in the sidebar and as links to the "next" doc. Because previewing docs on different branches sometime requires topics that are not available on the `main` branch yet, we'll omit topics with no docs on the frontend so they can still be viewed on `/docs/dynamic` routes.
closes payloadcms/payload#13863

fix: omit topics with no docs
