src/app/[...slug]/head.tsx, src/app/[...slug]/page.tsx, src/app/blog/[slug]/head.tsx, src/app/blog/[slug]/page.tsx, src/app/case-studies/[slug]/head.tsx, src/app/case-studies/[slug]/page.tsx, src/app/docs/[topic]/[doc]/head.tsx, src/app/docs/[topic]/[doc]/page.tsx, src/app/not-found.tsx, src/components/ErrorMessage/index.tsx, src/components/Highlight/index.module.scss, src/components/Highlight/index.tsx, src/graphql/index.ts
- Adds `not-found.tsx` and wires up page 
- Adds `forceDark` prop to Highlight component so I can use it 
This is how it looks in light/dark mode:
=> feat: sets up 404 pages

src/app/community-help/render.tsx, src/components/AuthorTag/index.tsx
- uses nextLink on community help archive to prevent hard reload
- opens twitter tags in new tab
=> fix: updates community help links

src/components/Button/index.tsx, src/components/Hero/Livestream/index.module.scss, src/components/Hero/Livestream/index.tsx, src/components/Hero/index.tsx, src/graphql/pages.ts, src/payload-types.ts, src/utilities/format-date-time.ts
Builds the livestream hero.
Design: https://www.figma.com/file/Vhecii2Q0irqeaXwYEKqR9/Website-2.0?node-id=4028:2470&t=UzQHKtQEiZrPpBIQ-0
=> feat: builds livestream hero

src/app/cloud/settings/page.module.scss, src/app/cloud/settings/page.tsx, src/forms/Label/index.module.scss
=> chore: separates account settings into two views

package.json, src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/(build-settings)/client_page.tsx, src/app/new/(checkout)/Checkout.tsx, src/app/new/import/ImportProject.tsx, src/components/BranchSelector/index.tsx, src/components/InstallationSelector/index.tsx, src/forms/fields/Select/index.tsx, src/graphql/project.ts, src/payload-cloud-types.ts, src/utilities/use-check-token.ts, src/utilities/use-get-installs.ts, src/utilities/use-get-repos.ts, yarn.lock
Dynamically populates repository branches as a select field to avoid discrepancies during build. This applies to both the checkout and project settings views.
=> feat: dynamic branch names

src/app/cloud/[team-slug]/settings/client_page.tsx, src/components/TeamDrawer/DrawerContent.tsx, src/components/UniqueSlug/index.tsx, src/components/UniqueSlug/reducer.ts
Displays the _validated and slugified_ slug to the user and ensures _that_ value is in form state instead of raw user input.
=> fix: automatically slugifies unique team and project slugs

src/app/new/(checkout)/Checkout.tsx, src/app/new/(checkout)/useDeploy.tsx, src/components/UniqueDomain/index.module.scss, src/components/UniqueDomain/index.tsx, src/components/UniqueDomain/reducer.ts, src/components/UniqueSlug/index.tsx, src/forms/fields/Text/index.module.scss, src/forms/fields/Text/index.tsx, src/payload-cloud-types.ts
Exposes `defaultDomain` at checkout to allow for customization prior to deployment.
=> feat: builds UniqueDomain component

src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/(build-settings)/client_page.tsx, src/app/cloud/[team-slug]/settings/client_page.tsx, src/components/InviteTeammates/index.tsx, src/components/TeamDrawer/DrawerContent.tsx, src/forms/fields/Select/index.tsx
Fixes a bug in the select field where it was not initializing `isMulti` values, and also not respecting arrays in the validation function. This was a problem in the team invitation component, where users were not able to invite teammates because the `roles` field had incorrect values.
=> fix: select field validation function

src/blocks/Pricing/index.module.scss, src/components/cards/PricingCard/index.module.scss, src/css/app.scss, src/css/queries.scss, src/css/vars.scss
=> fix: adjusts pricing card for very large screens

src/app/new/(checkout)/Checkout.tsx, src/app/new/clone/[template]/CloneTemplate.module.scss, src/app/new/clone/[template]/CloneTemplate.tsx, src/app/new/useCreateDraftProject.tsx, src/components/InstallationSelector/index.tsx, src/components/InstallationSelector/useGetInstalls.ts, src/forms/FormSubmissionError/index.tsx, src/utilities/use-get-repos.ts
=> chore: refines clone error handling

src/app/cloud/[team-slug]/[project-slug]/(tabs)/(overview)/infraOnline/index.module.scss, src/app/cloud/[team-slug]/[project-slug]/(tabs)/(overview)/infraOnline/index.tsx, src/graphics/ClockIcon/index.tsx, src/graphics/CommitIcon/index.tsx, src/utilities/format-date-time.ts
Rework InfraOnline component to include commit sha, message, and in-progress build/deploy status.
Before (no current build info):
After:
=> feat: add current build indicator, sha, message

src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/domains/_components/ManageDomain/index.tsx
Removes the ability to update custom domains. Instead, users will simply delete and add a new domain.
=> fix: removes updateDomain, removes form

src/app/(pages)/blog/[slug]/AuthorsList/index.module.scss, src/app/(pages)/blog/[slug]/AuthorsList/index.tsx, src/app/(pages)/blog/[slug]/client_page.tsx, src/app/(pages)/blog/[slug]/index.module.scss, src/graphql/posts.ts, src/payload-types.ts
Supports multiple blog post authors and renders / links to twitter profiles.
=> feat: blog post authors list

src/components/MDX/components/LightDarkImage/index.module.scss, src/components/MDX/components/LightDarkImage/index.tsx, src/components/MDX/components/index.ts
Add mdx component to render light and dark mode image in docs
=> feat: add mdx component to render light and dark mode image in docs

src/app/new/import/ImportProject.tsx
=> Fix: adds onClick event to button to createDraftProject

src/app/new/page.tsx
=> fix: properly threads team slug through new project block

next.config.js, src/components/MDX/components/VideoDrawer/index.module.scss, src/components/MDX/components/VideoDrawer/index.tsx, src/components/MDX/components/index.ts, src/icons/PlayIcon/index.tsx
**MOCKUP** - Figma design [here](https://www.figma.com/file/Vhecii2Q0irqeaXwYEKqR9/Website-2.0?type=design&t=YBHzOh1bFUk6vsix-6):
docs callout
drawer
hover states & mobile
**FINAL - Built component:**
docs callout
drawer
light mode
mobile
smallest mobile
=> feat: builds video widget for documentation

.env.example, package.json, src/app/(pages)/[...slug]/page.tsx, src/app/(pages)/blog/[slug]/AuthorsList/index.tsx, src/app/(pages)/blog/[slug]/page.tsx, src/app/_graphql/index.ts, src/app/_graphql/pages.ts, src/app/_graphql/posts.ts, src/app/_graphql/token.ts, src/app/api/exit-preview/route.ts, src/app/api/preview/route.ts, src/app/api/revalidate/route.ts, yarn.lock
=> feat: draft preview

src/app/_components/Indicator/index.module.scss, src/app/_components/Indicator/index.tsx, src/app/cloud/[team-slug]/[project-slug]/(tabs)/(overview)/DeploymentLogs/index.tsx, src/app/cloud/[team-slug]/[project-slug]/(tabs)/(overview)/InfraOffline/index.tsx, src/app/cloud/[team-slug]/[project-slug]/(tabs)/(overview)/InfraOnline/index.tsx, src/app/cloud/[team-slug]/[project-slug]/(tabs)/logs/page_client.tsx, src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/domains/page_client.tsx, src/app/cloud/_components/Tabs/index.module.scss, src/utilities/use-websocket.tsx
=> chore: refactor infra screens and deploy logging

src/app/(pages)/login/page_client.tsx
Namaste Everyone,
I've identified an **Open Redirection** vulnerability in the login process. Attackers can manipulate the '**redirect**' parameter to lead users to malicious site after successful login.
- Vulnerability: Open redirection due to weak '**redirect**' parameter validation.
- Risk: Potential unauthorized redirection to malicious sites after login.
I've fixed this by implementing trusted route validation for the 'redirect' parameter.
Best regards,
[Ashokasec](https://linkedin.com/in/ashokasec) (Shivam Gupta)
=> Fixed Open Redirection Vulnerability

src/app/(pages)/blog/[slug]/BlogPost/index.tsx, src/blocks/RelatedPosts/index.tsx
Related Posts types did not include strings, this adds those definitions and adds a type check to the component.
=> Fix: properly checks types on related posts

src/components/Hero/Home/index.module.scss, src/css/app.scss, src/css/queries.scss, src/css/vars.scss
Before:
https://github.com/payloadcms/website/assets/35232443/856b1d00-e975-429c-b39c-1f7822e4be20
After:
https://github.com/payloadcms/website/assets/35232443/9d639623-573f-40ab-88ff-f9be0b0a36ae
=> fix: adjusts home hero styles for small height breakpoint

src/app/api/star-count/route.ts, src/utilities/use-star-count.ts
Move star count to route, so it can be cached.
=> feat: move star count to route

src/app/cloud/[team-slug]/[project-slug]/(tabs)/file-storage/page_client.tsx, src/components/CopyToClipboard/index.tsx
Adds copy button to copy file storage env values.
=> feat: add copy button for file storage env values

src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/ownership/page_client.tsx
Project ownership changes are now restricted to admins.
=> feat: disallow project ownership changes

src/components/Hero/ContentMedia/index.module.scss, src/components/Hero/ContentMedia/index.tsx, src/payload-types.ts
CMS PR: https://github.com/payloadcms/website-cms/pull/53
Old:
New:
Those buttons should be fixed in the other CTA PR
=> feat: updates media-content hero to new design

src/app/_graphql/pages.ts, src/components/Breadcrumbs/index.module.scss, src/components/Breadcrumbs/index.tsx, src/components/Hero/ContentMedia/index.module.scss, src/components/Hero/ContentMedia/index.tsx, src/components/Hero/Default/index.module.scss, src/components/Hero/Default/index.tsx, src/payload-types.ts
=> feat: update default hero

src/components/Button/index.module.scss, src/components/Button/index.tsx, src/components/Hero/CenteredContent/index.module.scss, src/components/Hero/CenteredContent/index.tsx, src/components/Hero/index.tsx
CMS PR: https://github.com/payloadcms/website-cms/pull/56
=> feat: adds new centered-content hero style

src/app/_graphql/blocks.ts, src/blocks/CodeFeature/index.module.scss, src/blocks/CodeFeature/index.tsx, src/components/Code/index.module.scss, src/components/Code/index.tsx, src/css/app.scss, src/css/vars.scss, src/payload-types.ts
CMS PR: https://github.com/payloadcms/website-cms/pull/58
Old:
New:
=> feat: updates code feature block ui

src/css/app.scss, src/css/type.scss
Adds changes to the headline and body text sizes for each breakpoint, as well as adjustments to the `--gutter-h` variable for horizontal spacing.
=> chore: refines responsive styles for typography and gutters

src/blocks/CallToAction/index.module.scss, src/blocks/CallToAction/index.tsx, src/blocks/CodeFeature/index.module.scss, src/components/Button/index.module.scss, src/components/Button/index.tsx
=> feat: update button styles

src/blocks/MediaBlock/index.module.scss, src/blocks/MediaBlock/index.tsx
Updates media block to use grid and new block wrapper
=> chore: update media block

src/app/_graphql/blocks.ts, src/app/_graphql/case-studies.ts, src/app/_graphql/pages.ts, src/blocks/Statement/index.module.scss, src/blocks/Statement/index.tsx, src/components/RenderBlocks/index.tsx, src/payload-types.ts
=> feat: adds statement block ui

src/app/_graphql/blocks.ts, src/blocks/ContentGrid/index.module.scss, src/blocks/ContentGrid/index.tsx, src/payload-types.ts
CMS: https://github.com/payloadcms/website-cms/pull/70
=> feat: update content grid block

src/app/_graphql/blocks.ts, src/blocks/CardGrid/index.module.scss, src/blocks/CardGrid/index.tsx, src/components/BackgroundScanline/index.module.scss, src/components/cards/SquareCard/index.module.scss, src/components/cards/SquareCard/index.tsx, src/components/cards/types.ts, src/css/app.scss, src/payload-types.ts
Updates the card grid block with new styles and hover states
=> Chore: card grid update

src/blocks/CallToAction/index.tsx, src/components/Button/index.module.scss, src/components/Button/index.tsx
=> chore: sizing updates for cta block buttons

src/app/(pages)/blog/[slug]/AuthorsList/index.module.scss, src/app/(pages)/blog/[slug]/AuthorsList/index.tsx, src/app/(pages)/blog/[slug]/BlogPost/index.module.scss, src/app/(pages)/docs/client_layout.tsx, src/app/(pages)/docs/index.module.scss, src/app/community-help/ArchiveSearchBar/index.module.scss, src/app/community-help/index.module.scss, src/blocks/Callout/index.module.scss, src/blocks/CaseStudyParallax/index.module.scss, src/blocks/CaseStudyParallax/index.tsx, src/blocks/CodeFeature/index.module.scss, src/blocks/Pricing/index.module.scss, src/components/Code/index.module.scss, src/components/DiscordGitBody/index.module.scss, src/components/DiscordUsersPill/index.module.scss, src/components/Footer/index.module.scss, src/components/GithubStarsPill/index.module.scss, src/components/Header/DesktopNav/index.module.scss, src/components/Header/MobileNav/index.module.scss, src/components/Header/index.module.scss, src/components/cards/ContentMediaCard/index.module.scss, src/css/app.scss, src/css/docsearch.scss, src/css/type.scss, src/forms/Error/index.module.scss, src/forms/fields/shared.scss, src/icons/index.module.scss
Many components throughout the site were font sizes with random calculations. This PR simplifies a lot of those styles for more global consistency. Also cleaned up some unused classes.
=> chore: typography fine tuning

src/app/(pages)/docs/(current)/client_layout.tsx, src/components/VersionSelector/index.module.scss
=> fix: version switcher in mobile docs nav

src/app/(cloud)/cloud/[team-slug]/(tabs)/settings/(tabs)/invoices/page_client.tsx, src/app/(cloud)/cloud/_api/fetchInvoices.ts
Adds stripe-hosted invoice link to invoices page
=> feat: add invoice link

package.json
Adjust `--ref` values for fetch docs script after the branch renaming in the payload repo.
=> feat(docs): update fetch-docs after branch rename

src/app/_data/index.ts, src/components/DocsNavigation/index.tsx, src/components/Drawer/index.module.scss, src/components/Feedback/index.module.scss, src/components/Feedback/index.tsx, src/components/MDX/components/CustomTable/index.module.scss, src/components/MDX/components/CustomTable/index.tsx, src/components/MDX/components/RestExamples/index.module.scss, src/components/MDX/components/RestExamples/index.tsx, src/components/MDX/components/TableWithDrawers/index.tsx, src/components/RenderDocs/index.tsx, src/payload.config.ts
- Adds a form to the docs pages to leave feedback for improvements.
- Adds a link to view source of each doc.
- Various style fixes.
=> feat: docs feedback form

src/app/(frontend)/(cloud)/cloud/[team-slug]/[project-slug]/(tabs)/settings/(build-settings)/page_client.tsx, src/app/(frontend)/(cloud)/new/(checkout)/Checkout.tsx
Add setting to enable/disable auto deploy on push for cloud projects.
=> feat: add auto deploy setting

src/components/DocsNavigation/index.tsx
https://github.com/payloadcms/website/pull/439/files#r1995626688
=> fix: allow collapse sections in nav

src/app/(frontend)/(pages)/posts/[category]/[slug]/page.tsx, src/app/(frontend)/api/og/route.tsx, src/app/_data/index.ts, src/collections/Categories.ts, src/collections/Posts.ts, src/components/Archive/index.tsx, src/components/FeaturedBlogPost/index.tsx, src/components/Post/index.tsx, src/components/RelatedResources/index.module.scss, src/components/RelatedResources/index.tsx, src/components/blocks/RelatedPosts/index.tsx, src/components/cards/ContentMediaCard/index.tsx, src/payload-types.ts
Improves the setting of different post media uses: Opengraph images, archive thumbnails, and featured media on single posts.
=> chore: Better control of post media settings

src/app/(frontend)/(cloud)/cloud/_api/fetchInstalls.ts, src/app/(frontend)/(cloud)/join-team/page_client.tsx, src/app/(frontend)/(cloud)/new/(checkout)/Checkout.tsx, src/app/(frontend)/(cloud)/new/(checkout)/createSubscription.ts, src/app/(frontend)/(cloud)/new/(checkout)/deploy.tsx, src/app/(frontend)/types.ts
Improve API response shapes across multiple endpoints.
=> chore: improve response shapes

redirects.js, src/app/(frontend)/(cloud)/cloud/(tabs)/page.module.scss, src/app/(frontend)/(cloud)/cloud/(tabs)/page_client.tsx, src/app/(frontend)/(cloud)/cloud/[team-slug]/(tabs)/page.module.scss, src/app/(frontend)/(cloud)/cloud/[team-slug]/(tabs)/page_client.tsx, src/app/(frontend)/(cloud)/cloud/_components/TeamSelector/index.tsx, src/app/(frontend)/(cloud)/new/(checkout)/Checkout.tsx, src/app/(frontend)/(cloud)/new/layout.tsx, src/app/_data/me.ts, src/app/_data/team.ts, src/payload-cloud-types.ts
Adds functionality for allowing enterprise customers to create new deployments.
=> chore: conditionally allow new projects for cloud

src/collections/Docs/topicOrder.ts
=> docs: remove payload cloud
